<?php
/**
 *  Plugin Name: Motivational Quotes Widget
 *  Description: Displays a motivational quote each day in a widget.
 *  Version: 1.0
 *  Author: Kire
 */


class Motivational_Quotes_Widget {
    public function __construct()
    {
        add_action('admin_menu', array($this, 'add_admin_menu'));
        add_action('admin_init', array($this, 'add_register_settings'));
        add_action('wp_enqueue_scripts', array($this, 'load_assets'));
    }

    public function add_admin_menu()
    {
        add_menu_page(
                'Motivational daily quotes settings',
            'Motivation qoutes',
            'manage_options',
            'motivational_daily_quotes',
            array($this, 'render_form')
        );
    }

    public function render_form()
    {
        settings_errors();
        ?>
        <div class="container">
            <h1>Motivational quotes</h1>

            <form method="POST" action="options.php">
                <?php settings_fields('motivational_quotes'); ?>
                <?php do_settings_fields('motivational_quotes', 'default'); ?>
                <?php submit_button(); ?>
            </form>
            <hr>
            <h2>Existing quotes</h2>
            <?php $this->display_quotes(); ?>
        </div>
        <?php
    }

    public function add_register_settings()
    {
        register_setting('motivational_quotes', 'motivational_quotes', array($this, 'save_quote_in_database'));

        add_settings_field('motivational-quote', '', array($this, 'create_text_area'), 'motivational_quotes');
    }

    public function create_text_area()
    { ?>
         <label class="motivational-quote-label" for="motivational-quote"></label>
             <textarea name="motivational_quotes" class="motivational-quote-input" id="motivational-quote" placeholder="Enter your motivational quote"></textarea>

        <?php
    }

    public function save_quote_in_database($input)
    {
        $quotes = get_option('motivational_quotes');
        $quotes[] = sanitize_textarea_field($input);
        return $quotes;
    }

    public function display_quotes()
    {
        $quotes = get_option('motivational_quotes');
        foreach ($quotes as $quote) {
            echo '<h4>'.$quote . "</h4>";
        }
    }


    public function load_assets()
    {
        wp_enqueue_style('motivational-quotes-style', plugin_dir_url(__FILE__) . 'css/motivational-quotes-style.css');
    }
}

$motivational_quotes_widget = new Motivational_Quotes_Widget();

class Motivational_Daily_Quotes_Widget extends WP_Widget
{
    public function __construct()
    {
        parent::__construct('motivational-daily-quotes', 'Motivational daily quotes');
        add_action('widgets_init', function (){
            register_widget('Motivational_Daily_Quotes_Widget');
        });
    }

    public function widget( $args, $instance ) {
        echo $args['before_widget'];
        echo $args['before_title'] . apply_filters( 'widget_title', 'Daily quote' ) . $args['after_title'];


        $quote = $this->get_daily_quote();

        echo '<p class="blockquote"><em>"' . $quote . '"</em></p>';

        echo $args['after_widget'];
    }

    private function get_daily_quote() {
        $quote_transient = get_transient( 'daily_motivational_quote8' );
        if ( false === $quote_transient ) {
            $quotes = get_option( 'motivational_quotes' );
            $quote = $quotes[array_rand($quotes)];
            set_transient( 'daily_motivational_quote8', $quote, DAY_IN_SECONDS);
        } else {
            $quote = $quote_transient;
        }

        return $quote;
    }

    public function form($instance)
    {
        return parent::form($instance); // TODO: Change the autogenerated stub
    }

    public function update($new_instance, $old_instance)
    {
        return parent::update($new_instance, $old_instance); // TODO: Change the autogenerated stub
    }
}

$motivational_daily_quotes_widget = new Motivational_Daily_Quotes_Widget();